from generators import (
    gerar_varejo, gerar_financeiro, gerar_saude, gerar_tecnologia,
    gerar_educacao, gerar_logistica, gerar_energia, gerar_telecom,
    gerar_industria, gerar_agronegocio, gerar_hotelaria, gerar_streaming,
    gerar_ecommerce, gerar_rh, gerar_mobilidade, gerar_fintech,
    gerar_turismo, gerar_imobiliario, gerar_seguros, gerar_construcao,
    gerar_mineracao, gerar_alimenticio, gerar_juridico, gerar_esportes,
    gerar_saas_b2b, gerar_crm, gerar_farmaceutico, gerar_marketing,
    gerar_petroleo, gerar_governo, gerar_portabilidade_claro,
    gerar_aviacao, gerar_pet, gerar_games, gerar_saneamento, gerar_transporte,
    gerar_moda, gerar_eventos, gerar_laboratorio, gerar_franquias, gerar_condominio,
    gerar_saude_mental, gerar_florestal, gerar_startup, gerar_audiovisual, gerar_pesca,
    gerar_textil, gerar_arquitetura, gerar_viagem_corp, gerar_espacial, gerar_beleza,
    gerar_logistica_urbana,
    # ═══════ NOVOS SETORES ═══════
    gerar_agtech, gerar_economia_circular, gerar_biotecnologia,
    gerar_odontologia, gerar_academia, gerar_ciberseguranca,
    gerar_locadora, gerar_restaurante,
    # ═══════ +10 NOVOS SETORES ═══════
    gerar_ensino_superior, gerar_funeraria, gerar_agencia_publicidade,
    gerar_pecuaria, gerar_homecare, gerar_apostas_esportivas,
    gerar_coworking, gerar_editora, gerar_drones, gerar_frigorifico,
    # ═══════ +10 NOVOS SETORES (LOTE 3) ═══════
    gerar_concessionaria, gerar_museus, gerar_autopecas, gerar_consultoria,
    gerar_vinicola, gerar_cinema, gerar_metro, gerar_grafica,
    gerar_seguranca_privada, gerar_locacao_temporada,
    # ═══════ +10 NOVOS SETORES (LOTE 4) ═══════
    gerar_consorcio, gerar_metalurgia, gerar_papelaria, gerar_terceiro_setor,
    gerar_call_center, gerar_assistencia_tecnica, gerar_locacao_equipamentos,
    gerar_cartorio, gerar_piscina_spa, gerar_datacenter,
    # ═══════ +10 NOVOS SETORES (LOTE 5) ═══════
    gerar_correios, gerar_blockchain, gerar_cooperativa_credito, gerar_optica,
    gerar_joalheria, gerar_marcenaria, gerar_reciclagem, gerar_casa_loterica,
    gerar_estacionamento, gerar_leilao,
    # ═══════ +50 NOVOS SETORES (LOTE 6) ═══════
    gerar_agencia_cambio, gerar_ambulancia, gerar_apicultura, gerar_armazenagem,
    gerar_artesanato, gerar_auditoria, gerar_barbearia, gerar_biocombustiveis,
    gerar_buffet, gerar_cervejaria, gerar_clube_assinatura, gerar_comercio_exterior,
    gerar_contabilidade, gerar_corretora_investimentos, gerar_cursinho, gerar_delivery,
    gerar_energia_solar, gerar_escola_idiomas, gerar_escola_musica, gerar_estudio_tatuagem,
    gerar_fabrica_embalagens, gerar_farmacia_manipulacao, gerar_feira_livre, gerar_ferrovia_carga,
    gerar_floricultura, gerar_food_truck, gerar_igreja, gerar_industria_moveleira,
    gerar_industria_naval, gerar_lavanderia, gerar_manutencao_industrial, gerar_motoboy,
    gerar_multipropriedade, gerar_plano_saude, gerar_padaria, gerar_parque_diversoes,
    gerar_porto, gerar_posto_combustivel, gerar_radio_podcast, gerar_relacoes_publicas,
    gerar_serralheria, gerar_limpeza, gerar_sindicato, gerar_taxi_aereo,
    gerar_telemedicina, gerar_transporte_escolar, gerar_usina_acucar_etanol, gerar_vending_machine,
    gerar_viveiro_paisagismo, gerar_zoologico
)

# Configuração da página Streamlit
PAGE_CONFIG = {
    "page_title": "BI Data Generator PRO",
    "page_icon": "📊",
    "layout": "wide",
    "initial_sidebar_state": "expanded"
}

# Configurações do slider de linhas
SLIDER_MIN = 100
SLIDER_MAX = 100000
SLIDER_DEFAULT = 5000
SLIDER_STEP = 100

# ═══════════════════════════════════════════════════════════════
# Dicionário de setores disponíveis (100 setores) — ordem alfabética
# ═══════════════════════════════════════════════════════════════
SETORES = {
    "🏋️ Academia & Fitness":          gerar_academia,
    "💱 Agência de Câmbio": gerar_agencia_cambio,
    "📢 Agência de Publicidade":      gerar_agencia_publicidade,
    "🌾 Agronegócio":                 gerar_agronegocio,
    "🌱 AgTech":                      gerar_agtech,
    "🍔 Alimentos & Bebidas":         gerar_alimenticio,
    "🚑 Ambulância & Remoção": gerar_ambulancia,
    "🐝 Apicultura": gerar_apicultura,
    "🎰 Apostas Esportivas & iGaming": gerar_apostas_esportivas,
    "🏬 Armazenagem & Self Storage": gerar_armazenagem,
    "🏛️ Arquitetura & Design":        gerar_arquitetura,
    "🧶 Artesanato": gerar_artesanato,
    "🔩 Assistência Técnica de Eletrônicos": gerar_assistencia_tecnica,
    "🎬 Audiovisual & Produtora":     gerar_audiovisual,
    "🕵️ Auditoria & Compliance": gerar_auditoria,
    "🔧 Autopeças & Oficina Mecânica": gerar_autopecas,
    "✈️ Aviação Civil":               gerar_aviacao,
    "💈 Barbearia": gerar_barbearia,
    "💄 Beleza & Estética":           gerar_beleza,
    "🌽 Biocombustíveis": gerar_biocombustiveis,
    "🧬 Biotecnologia":               gerar_biotecnologia,
    "🪙 Blockchain & Criptomoedas":   gerar_blockchain,
    "🍱 Buffet & Cerimonial": gerar_buffet,
    "📞 Call Center & BPO":           gerar_call_center,
    "📜 Cartório & Serviços Notariais": gerar_cartorio,
    "🎫 Casa Lotérica & Correspondente Bancário": gerar_casa_loterica,
    "🍺 Cervejaria Artesanal": gerar_cervejaria,
    "🔐 Cibersegurança":              gerar_ciberseguranca,
    "🎥 Cinema & Exibição":           gerar_cinema,
    "🎁 Clube de Assinaturas": gerar_clube_assinatura,
    "🌐 Comércio Exterior": gerar_comercio_exterior,
    "🚙 Concessionária de Veículos":  gerar_concessionaria,
    "🏢 Condomínio & Facilities":     gerar_condominio,
    "🧾 Consórcios":                  gerar_consorcio,
    "🏗️ Construção Civil":            gerar_construcao,
    "📊 Consultoria Empresarial":     gerar_consultoria,
    "🧮 Contabilidade": gerar_contabilidade,
    "💳 Cooperativa de Crédito":      gerar_cooperativa_credito,
    "📦 Correios & Encomendas":       gerar_correios,
    "📈 Corretora de Investimentos": gerar_corretora_investimentos,
    "🪑 Coworking & Espaços Compartilhados": gerar_coworking,
    "🤝 CRM":                         gerar_crm,
    "📝 Cursinho Preparatório": gerar_cursinho,
    "🖥️ Data Center & Cloud Hosting": gerar_datacenter,
    "🛵 Delivery de Comida": gerar_delivery,
    "🚁 Drones & Serviços Aéreos":    gerar_drones,
    "🏪 E-commerce":                  gerar_ecommerce,
    "♻️ Economia Circular":           gerar_economia_circular,
    "📖 Editora & Publicação":        gerar_editora,
    "📚 Educação":                    gerar_educacao,
    "⚡ Energia":                     gerar_energia,
    "☀️ Energia Solar": gerar_energia_solar,
    "🎓 Ensino Superior":             gerar_ensino_superior,
    "🗣️ Escola de Idiomas": gerar_escola_idiomas,
    "🎼 Escola de Música": gerar_escola_musica,
    "🚀 Espacial & Aeroespacial":     gerar_espacial,
    "🏟️ Esportes":                   gerar_esportes,
    "🅿️ Estacionamento & Zona Azul":  gerar_estacionamento,
    "🖋️ Estúdio de Tatuagem": gerar_estudio_tatuagem,
    "🎉 Eventos & Entretenimento":    gerar_eventos,
    "📦 Fábrica de Embalagens": gerar_fabrica_embalagens,
    "💊 Farmacêutico":                gerar_farmaceutico,
    "⚗️ Farmácia de Manipulação": gerar_farmacia_manipulacao,
    "🥬 Feira Livre & Mercado Municipal": gerar_feira_livre,
    "🚂 Ferrovia de Carga": gerar_ferrovia_carga,
    "💰 Financeiro":                  gerar_financeiro,
    "🏦 Fintech":                     gerar_fintech,
    "🌲 Florestal & Papel":           gerar_florestal,
    "💐 Floricultura": gerar_floricultura,
    "🌮 Food Truck": gerar_food_truck,
    "🏷️ Franquias":                  gerar_franquias,
    "🥩 Frigorífico & Processamento de Carnes": gerar_frigorifico,
    "⚰️ Funerária & Serviços Funerários": gerar_funeraria,
    "🎮 Games & eSports":             gerar_games,
    "🏛️ Governo & Setor Público":    gerar_governo,
    "🖨️ Gráfica & Comunicação Visual": gerar_grafica,
    "🩺 Home Care":                   gerar_homecare,
    "🏨 Hotelaria":                   gerar_hotelaria,
    "⛪ Igreja & Templos Religiosos": gerar_igreja,
    "🏠 Imobiliário":                 gerar_imobiliario,
    "🏭 Indústria":                   gerar_industria,
    "🛋️ Indústria Moveleira": gerar_industria_moveleira,
    "🚢 Indústria Naval": gerar_industria_naval,
    "💍 Joalheria & Relojoaria":      gerar_joalheria,
    "⚖️ Jurídico":                   gerar_juridico,
    "🔬 Laboratório & Diagnóstico":   gerar_laboratorio,
    "🧺 Lavanderia": gerar_lavanderia,
    "🔨 Leilão":                      gerar_leilao,
    "🛠️ Locação de Equipamentos":     gerar_locacao_equipamentos,
    "🏖️ Locação por Temporada":       gerar_locacao_temporada,
    "🚗 Locadora de Veículos":        gerar_locadora,
    "🚚 Logística":                   gerar_logistica,
    "🚴 Logística Urbana":            gerar_logistica_urbana,
    "🛠️ Manutenção Industrial": gerar_manutencao_industrial,
    "🪵 Marcenaria & Móveis Planejados": gerar_marcenaria,
    "📣 Marketing Digital":           gerar_marketing,
    "⚙️ Metalurgia & Siderurgia":     gerar_metalurgia,
    "🚇 Metrô & Trem Urbano":         gerar_metro,
    "📲 Migração Claro Brasil (Portabilidade)": gerar_portabilidade_claro,
    "⛏️ Mineração":                  gerar_mineracao,
    "🚗 Mobilidade":                  gerar_mobilidade,
    "👗 Moda & Vestuário":            gerar_moda,
    "🏍️ Motoboy & App de Transporte": gerar_motoboy,
    "🏝️ Multipropriedade": gerar_multipropriedade,
    "🖼️ Museus & Cultura":            gerar_museus,
    "🦷 Odontologia":                 gerar_odontologia,
    "🗂️ Operadora de Plano de Saúde": gerar_plano_saude,
    "👓 Óptica":                      gerar_optica,
    "🥐 Padaria & Confeitaria": gerar_padaria,
    "📎 Papelaria & Material Escolar": gerar_papelaria,
    "🎡 Parque de Diversões": gerar_parque_diversoes,
    "🐄 Pecuária":                    gerar_pecuaria,
    "🐟 Pesca & Aquicultura":         gerar_pesca,
    "🐾 Pet & Veterinária":           gerar_pet,
    "🛢️ Petróleo & Gás":             gerar_petroleo,
    "🏊 Piscina & Spa":               gerar_piscina_spa,
    "⚓ Porto & Terminal Portuário": gerar_porto,
    "⛽ Posto de Combustível & Conveniência": gerar_posto_combustivel,
    "🎙️ Rádio & Podcast": gerar_radio_podcast,
    "🗑️ Reciclagem & Gestão de Resíduos": gerar_reciclagem,
    "🏢 Recursos Humanos":            gerar_rh,
    "📰 Relações Públicas": gerar_relacoes_publicas,
    "🍽️ Restaurantes & Food Service": gerar_restaurante,
    "☁️ SaaS B2B":                   gerar_saas_b2b,
    "💧 Saneamento & Água":           gerar_saneamento,
    "🏥 Saúde":                       gerar_saude,
    "🧠 Saúde Mental":                gerar_saude_mental,
    "🔒 Segurança Privada":           gerar_seguranca_privada,
    "🛡️ Seguros":                    gerar_seguros,
    "⚒️ Serralheria": gerar_serralheria,
    "🧹 Serviços de Limpeza": gerar_limpeza,
    "🪧 Sindicato & Associação de Classe": gerar_sindicato,
    "🦄 Startups & Venture Capital":  gerar_startup,
    "🎬 Streaming":                   gerar_streaming,
    "🛩️ Táxi Aéreo & Aviação Executiva": gerar_taxi_aereo,
    "💻 Tecnologia":                  gerar_tecnologia,
    "📡 Telecom":                     gerar_telecom,
    "🖥️ Telemedicina": gerar_telemedicina,
    "🤲 Terceiro Setor & ONGs":       gerar_terceiro_setor,
    "🧵 Têxtil & Confecção":          gerar_textil,
    "🚛 Transporte":                  gerar_transporte,
    "🚌 Transporte Escolar": gerar_transporte_escolar,
    "✈️ Turismo":                     gerar_turismo,
    "🍬 Usina de Açúcar & Etanol": gerar_usina_acucar_etanol,
    "🛒 Varejo":                      gerar_varejo,
    "🥤 Vending Machine & Autoatendimento": gerar_vending_machine,
    "✈️ Viagens Corporativas":        gerar_viagem_corp,
    "🍷 Vinícola & Vitivinicultura":  gerar_vinicola,
    "🌳 Viveiro & Paisagismo": gerar_viveiro_paisagismo,
    "🦁 Zoológico & Aquário": gerar_zoologico,
}

# ═══════════════════════════════════════════════════════════════
# Informações para os flip-cards da tela inicial (100 setores) — ordem alfabética
# ═══════════════════════════════════════════════════════════════
SETORES_INFO = [
    ("🏋️", "Academia & Fitness",         "Check-ins, alunos, instrutores, pagamentos e avaliações físicas"),
    ("💱", "Agência de Câmbio", "Operações de câmbio, moedas, cotações e taxas de serviço"),
    ("📢", "Agência de Publicidade",     "Projetos, campanhas de mídia, equipe e clientes"),
    ("🌾", "Agronegócio",                 "Safras, culturas, propriedades e insumos"),
    ("🌱", "AgTech",                      "Sensores IoT, drones, monitoramento e agricultura de precisão"),
    ("🍔", "Alimentos & Bebidas",         "Produção, plantas, produtos e fornecedores"),
    ("🚑", "Ambulância & Remoção", "Chamados de emergência, ambulâncias, equipes e tempo de resposta"),
    ("🐝", "Apicultura", "Apiários, colmeias, colheita de mel e sanidade"),
    ("🎰", "Apostas Esportivas & iGaming", "Apostas, jogadores, eventos esportivos e transações"),
    ("🏬", "Armazenagem & Self Storage", "Unidades, boxes, contratos e ocorrências de armazenagem"),
    ("🏛️", "Arquitetura & Design",       "Projetos, serviços, honorários e gestão de obras"),
    ("🧶", "Artesanato", "Artesãos, produtos, vendas por canal e produção"),
    ("🔩", "Assistência Técnica de Eletrônicos", "Ordens de serviço, técnicos, peças e reparos"),
    ("🎬", "Audiovisual & Produtora",     "Produções, orçamentos, recursos e bilheteria"),
    ("🕵️", "Auditoria & Compliance", "Auditores, clientes, achados e não conformidades"),
    ("🔧", "Autopeças & Oficina Mecânica", "Peças, serviços, clientes e canais de venda"),
    ("✈️", "Aviação Civil",               "Voos, passageiros, aeronaves e aeroportos"),
    ("💈", "Barbearia", "Barbeiros, unidades, atendimentos e assinaturas"),
    ("💄", "Beleza & Estética",           "Vendas, serviços, agenda e salões parceiros"),
    ("🌽", "Biocombustíveis", "Usinas, matérias-primas, produção e vendas de combustível"),
    ("🧬", "Biotecnologia",               "Genômica, CRISPR, pesquisa e experimentos laboratoriais"),
    ("🪙", "Blockchain & Criptomoedas",   "Transações, moedas, usuários e carteiras digitais"),
    ("🍱", "Buffet & Cerimonial", "Eventos, cardápios, fornecedores e cerimonial"),
    ("📞", "Call Center & BPO",           "Atendimentos, atendentes, clientes e avaliação de qualidade"),
    ("📜", "Cartório & Serviços Notariais", "Atos notariais, tabeliães, clientes e protestos"),
    ("🎫", "Casa Lotérica & Correspondente Bancário", "Transações, apostas de loteria, unidades e serviços"),
    ("🍺", "Cervejaria Artesanal", "Rótulos, pontos de venda, produção e vendas"),
    ("🔐", "Cibersegurança",              "Incidentes, vulnerabilidades, ativos e SLA de resposta (SOC)"),
    ("🎥", "Cinema & Exibição",           "Sessões, filmes, salas e bomboniere"),
    ("🎁", "Clube de Assinaturas", "Assinantes, caixas temáticas, planos e envios"),
    ("🌐", "Comércio Exterior", "Produtos, países, importações e exportações"),
    ("🚙", "Concessionária de Veículos",  "Vendas, veículos, vendedores e test-drives"),
    ("🏢", "Condomínio & Facilities",     "Cotas, despesas, ocorrências e manutenção"),
    ("🧾", "Consórcios",                  "Parcelas, contemplações, grupos e cotistas"),
    ("🏗️", "Construção Civil",           "Obras, custos, materiais e fornecedores"),
    ("📊", "Consultoria Empresarial",     "Projetos, consultores, faturas e clientes"),
    ("🧮", "Contabilidade", "Contadores, clientes PJ, serviços e honorários"),
    ("💳", "Cooperativa de Crédito",      "Operações, cooperados, produtos e sobras distribuídas"),
    ("📦", "Correios & Encomendas",       "Envios, agências, serviços e ocorrências"),
    ("📈", "Corretora de Investimentos", "Assessores, clientes, ativos, ordens e carteiras"),
    ("🪑", "Coworking & Espaços Compartilhados", "Reservas, assinaturas, espaços e clientes"),
    ("🤝", "CRM",                         "Oportunidades, contas, contatos e atividades comerciais"),
    ("📝", "Cursinho Preparatório", "Professores, alunos, matrículas e simulados"),
    ("🖥️", "Data Center & Cloud Hosting", "Consumo, instâncias, clientes e incidentes"),
    ("🛵", "Delivery de Comida", "Restaurantes parceiros, entregadores, pedidos e avaliações"),
    ("🚁", "Drones & Serviços Aéreos",    "Missões, drones, manutenção e clientes"),
    ("🏪", "E-commerce",                  "Pedidos, clientes, produtos, fretes e pagamentos"),
    ("♻️", "Economia Circular",           "Reciclagem, logística reversa, créditos de carbono e ESG"),
    ("📖", "Editora & Publicação",        "Livros, vendas, canais e estoque"),
    ("📚", "Educação",                    "Matrículas, alunos, cursos e instrutores"),
    ("⚡", "Energia",                     "Consumo, medidores, subestações e tarifas"),
    ("☀️", "Energia Solar", "Instalações, clientes, geração e projetos fotovoltaicos"),
    ("🎓", "Ensino Superior",             "Matrículas, disciplinas, cursos e desempenho acadêmico"),
    ("🗣️", "Escola de Idiomas", "Professores, alunos, cursos, matrículas e avaliações"),
    ("🎼", "Escola de Música", "Professores, alunos, instrumentos, aulas e matrículas"),
    ("🚀", "Espacial & Aeroespacial",     "Missões, satélites, lançamentos e operações"),
    ("🏟️", "Esportes",                   "Partidas, atletas, clubes e competições"),
    ("🅿️", "Estacionamento & Zona Azul",  "Entradas, estacionamentos, clientes e multas"),
    ("🖋️", "Estúdio de Tatuagem", "Tatuadores, clientes, sessões e retornos"),
    ("🎉", "Eventos & Entretenimento",    "Ingressos, fornecedores, receitas e NPS"),
    ("📦", "Fábrica de Embalagens", "Produtos, clientes PJ, produção e pedidos"),
    ("💊", "Farmacêutico",                "Produtos, representantes, vendas e estoque"),
    ("⚗️", "Farmácia de Manipulação", "Farmacêuticos, clientes, fórmulas e insumos"),
    ("🥬", "Feira Livre & Mercado Municipal", "Feirantes, bancas, vendas e ocupação"),
    ("🚂", "Ferrovia de Carga", "Locomotivas, terminais, viagens de carga e manutenção"),
    ("💰", "Financeiro",                  "Transações bancárias, contas e agências"),
    ("🏦", "Fintech",                     "Transações, cartões, usuários, comerciantes e antifraude"),
    ("🌲", "Florestal & Papel",           "Talhões, espécies, colheita e carbono"),
    ("💐", "Floricultura", "Lojas, produtos, vendas e encomendas especiais"),
    ("🌮", "Food Truck", "Trucks, cardápio, vendas e eventos"),
    ("🏷️", "Franquias",                  "Unidades, royalties, taxas e faturamento"),
    ("🥩", "Frigorífico & Processamento de Carnes", "Abate, produtos, unidades e canais de venda"),
    ("⚰️", "Funerária & Serviços Funerários", "Atendimentos, serviços, planos preventivos e clientes"),
    ("🎮", "Games & eSports",             "Partidas, jogadores, jogos e monetização in-game"),
    ("🏛️", "Governo & Setor Público",    "Despesas, receitas, licitações e contratos"),
    ("🖨️", "Gráfica & Comunicação Visual", "Pedidos, produção, produtos e clientes"),
    ("🩺", "Home Care",                   "Visitas, pacientes, profissionais e ocorrências"),
    ("🏨", "Hotelaria",                   "Reservas, hóspedes, hotéis, quartos e canais"),
    ("⛪", "Igreja & Templos Religiosos", "Membros, ministérios, dízimos e eventos"),
    ("🏠", "Imobiliário",                 "Vendas, aluguéis, imóveis e corretores"),
    ("🏭", "Indústria",                   "Produção, máquinas, insumos e operadores"),
    ("🛋️", "Indústria Moveleira", "Produtos, máquinas, produção e vendas"),
    ("🚢", "Indústria Naval", "Estaleiros, embarcações, etapas de construção e manutenção"),
    ("💍", "Joalheria & Relojoaria",      "Vendas, produtos, clientes e assistência técnica"),
    ("⚖️", "Jurídico",                   "Processos, advogados, clientes e tribunais"),
    ("🔬", "Laboratório & Diagnóstico",   "Exames, pacientes, laudos e convênios"),
    ("🧺", "Lavanderia", "Unidades, clientes B2B, pedidos e ocorrências"),
    ("🔨", "Leilão",                      "Lances, lotes, arrematantes e arrematações"),
    ("🛠️", "Locação de Equipamentos",     "Locações, equipamentos, manutenção e clientes"),
    ("🏖️", "Locação por Temporada",       "Reservas, imóveis, hóspedes e avaliações"),
    ("🚗", "Locadora de Veículos",        "Reservas, frota, clientes, multas e diárias"),
    ("🚚", "Logística",                   "Entregas, transportadoras, rotas e clientes"),
    ("🚴", "Logística Urbana",            "Entregas last mile, entregadores e SLA"),
    ("🛠️", "Manutenção Industrial", "Técnicos, clientes, ordens de serviço e peças"),
    ("🪵", "Marcenaria & Móveis Planejados", "Contratos, projetos, produção e clientes"),
    ("📣", "Marketing Digital",           "Campanhas, canais, performance e conversões"),
    ("⚙️", "Metalurgia & Siderurgia",     "Produção, fornos, produtos e vendas"),
    ("🚇", "Metrô & Trem Urbano",         "Validações, estações, linhas e ocorrências"),
    ("📲", "Migração Claro Brasil (Portabilidade)", "Migrações IN/OUT, serviços, operadoras e motivos de portabilidade"),
    ("⛏️", "Mineração",                  "Extrações, minas, minerais e equipamentos"),
    ("🚗", "Mobilidade",                  "Viagens, motoristas, passageiros, rotas e veículos"),
    ("👗", "Moda & Vestuário",            "Coleções, vendas, estoque e devoluções"),
    ("🏍️", "Motoboy & App de Transporte", "Motociclistas, clientes e corridas de entrega/passageiro"),
    ("🏝️", "Multipropriedade", "Resorts, unidades, proprietários, reservas e taxas"),
    ("🖼️", "Museus & Cultura",            "Visitas, exposições, eventos culturais e ingressos"),
    ("🦷", "Odontologia",                 "Consultas, dentistas, pacientes, procedimentos e convênios"),
    ("🗂️", "Operadora de Plano de Saúde", "Beneficiários, planos, prestadores, autorizações e mensalidades"),
    ("👓", "Óptica",                      "Vendas, produtos, clientes e exames de vista"),
    ("🥐", "Padaria & Confeitaria", "Lojas, produtos, vendas e produção"),
    ("📎", "Papelaria & Material Escolar", "Vendas, produtos, lojas e estoque"),
    ("🎡", "Parque de Diversões", "Brinquedos, ingressos e uso dos brinquedos"),
    ("🐄", "Pecuária",                    "Fazendas, rebanho, manejo e produção"),
    ("🐟", "Pesca & Aquicultura",         "Espécies, produção, qualidade e biomassa"),
    ("🐾", "Pet & Veterinária",           "Atendimentos, pets, tutores e serviços veterinários"),
    ("🛢️", "Petróleo & Gás",             "Produção, poços, plataformas e custos operacionais"),
    ("🏊", "Piscina & Spa",               "Serviços, clientes, técnicos e consumo de produtos químicos"),
    ("⚓", "Porto & Terminal Portuário", "Terminais, navios, atracações e movimentação de carga"),
    ("⛽", "Posto de Combustível & Conveniência", "Postos, combustíveis, abastecimentos e loja de conveniência"),
    ("🎙️", "Rádio & Podcast", "Programas, apresentadores, audiência e anúncios"),
    ("🗑️", "Reciclagem & Gestão de Resíduos", "Coletas, materiais, cooperativas e vendas de material"),
    ("🏢", "Recursos Humanos",            "Horas trabalhadas, funcionários, projetos e cargos"),
    ("📰", "Relações Públicas", "Clientes, veículos de mídia, assessoria e clipping"),
    ("🍽️", "Restaurantes & Food Service", "Pedidos, cardápio, unidades, reservas e delivery"),
    ("☁️", "SaaS B2B",                   "Assinaturas, MRR, churn, NPS e planos"),
    ("💧", "Saneamento & Água",           "Consumo, faturas, estações de tratamento e ligações"),
    ("🏥", "Saúde",                       "Atendimentos, pacientes, médicos e procedimentos"),
    ("🧠", "Saúde Mental",                "Sessões, profissionais, pacientes e diagnósticos"),
    ("🔒", "Segurança Privada",           "Escalações, vigilantes, clientes e ocorrências"),
    ("🛡️", "Seguros",                    "Apólices, segurados, corretores e sinistros"),
    ("⚒️", "Serralheria", "Clientes, produtos, pedidos e produção"),
    ("🧹", "Serviços de Limpeza", "Funcionários, contratos, atendimentos e insumos"),
    ("🪧", "Sindicato & Associação de Classe", "Associados, categorias, contribuições e benefícios"),
    ("🦄", "Startups & Venture Capital",  "Rodadas, valuations, MRR e métricas de crescimento"),
    ("🎬", "Streaming",                   "Plays, assinantes, conteúdos, artistas"),
    ("🛩️", "Táxi Aéreo & Aviação Executiva", "Aeronaves, pilotos, voos fretados e manutenção"),
    ("💻", "Tecnologia",                  "Contratos SaaS, clientes e planos"),
    ("📡", "Telecom",                     "Chamadas, assinantes, planos e torres"),
    ("🖥️", "Telemedicina", "Médicos, pacientes, teleconsultas e prescrições"),
    ("🤲", "Terceiro Setor & ONGs",       "Doações, projetos sociais, doadores e execução"),
    ("🧵", "Têxtil & Confecção",          "Fibras, produção, eficiência e clientes"),
    ("🚛", "Transporte",                  "Viagens, frota, combustível, manutenção e rentabilidade"),
    ("🚌", "Transporte Escolar", "Veículos, motoristas, alunos, rotas e mensalidades"),
    ("✈️", "Turismo",                     "Viagens, pacotes, agências e destinos"),
    ("🍬", "Usina de Açúcar & Etanol", "Usinas, talhões, moagem e produção"),
    ("🛒", "Varejo",                      "Vendas, clientes, produtos e filiais"),
    ("🥤", "Vending Machine & Autoatendimento", "Máquinas, produtos, vendas e reposição"),
    ("✈️", "Viagens Corporativas",        "Viajantes, custos, política de viagem e SLA"),
    ("🍷", "Vinícola & Vitivinicultura",  "Produção, vinhedos, vinhos e canais de venda"),
    ("🌳", "Viveiro & Paisagismo", "Plantas, clientes, vendas e projetos de paisagismo"),
    ("🦁", "Zoológico & Aquário", "Recintos, animais, ingressos e manejo"),
]

# Configurações de datas (opcional)
DATE_DEFAULT_START = "2023-01-01"
DATE_DEFAULT_END   = "2023-12-31"
