from generators import (
    gerar_varejo, gerar_financeiro, gerar_saude, gerar_tecnologia,
    gerar_educacao, gerar_logistica, gerar_energia, gerar_telecom,
    gerar_industria, gerar_agronegocio, gerar_hotelaria, gerar_streaming,
    gerar_ecommerce, gerar_rh, gerar_mobilidade, gerar_fintech,
    gerar_turismo, gerar_imobiliario, gerar_seguros, gerar_construcao,
    gerar_mineracao, gerar_alimenticio, gerar_juridico, gerar_esportes,
    gerar_saas_b2b, gerar_crm, gerar_farmaceutico, gerar_marketing,
    gerar_petroleo, gerar_governo, gerar_portabilidade_claro,
    gerar_aviacao, gerar_pet, gerar_games, gerar_saneamento, gerar_transporte,
    gerar_moda, gerar_eventos, gerar_laboratorio, gerar_franquias, gerar_condominio,
    gerar_saude_mental, gerar_florestal, gerar_startup, gerar_audiovisual, gerar_pesca,
    gerar_textil, gerar_arquitetura, gerar_viagem_corp, gerar_espacial, gerar_beleza,
    gerar_logistica_urbana,
    # ═══════ NOVOS SETORES ═══════
    gerar_agtech, gerar_economia_circular, gerar_biotecnologia,
    gerar_odontologia, gerar_academia, gerar_ciberseguranca,
    gerar_locadora, gerar_restaurante,
    # ═══════ +10 NOVOS SETORES ═══════
    gerar_ensino_superior, gerar_funeraria, gerar_agencia_publicidade,
    gerar_pecuaria, gerar_homecare, gerar_apostas_esportivas,
    gerar_coworking, gerar_editora, gerar_drones, gerar_frigorifico,
    # ═══════ +10 NOVOS SETORES (LOTE 3) ═══════
    gerar_concessionaria, gerar_museus, gerar_autopecas, gerar_consultoria,
    gerar_vinicola, gerar_cinema, gerar_metro, gerar_grafica,
    gerar_seguranca_privada, gerar_locacao_temporada,
    # ═══════ +10 NOVOS SETORES (LOTE 4) ═══════
    gerar_consorcio, gerar_metalurgia, gerar_papelaria, gerar_terceiro_setor,
    gerar_call_center, gerar_assistencia_tecnica, gerar_locacao_equipamentos,
    gerar_cartorio, gerar_piscina_spa, gerar_datacenter,
    # ═══════ +10 NOVOS SETORES (LOTE 5) ═══════
    gerar_correios, gerar_blockchain, gerar_cooperativa_credito, gerar_optica,
    gerar_joalheria, gerar_marcenaria, gerar_reciclagem, gerar_casa_loterica,
    gerar_estacionamento, gerar_leilao,
    # ═══════ +50 NOVOS SETORES (LOTE 6) ═══════
    gerar_agencia_cambio, gerar_ambulancia, gerar_apicultura, gerar_armazenagem,
    gerar_artesanato, gerar_auditoria, gerar_barbearia, gerar_biocombustiveis,
    gerar_buffet, gerar_cervejaria, gerar_clube_assinatura, gerar_comercio_exterior,
    gerar_contabilidade, gerar_corretora_investimentos, gerar_cursinho, gerar_delivery,
    gerar_energia_solar, gerar_escola_idiomas, gerar_escola_musica, gerar_estudio_tatuagem,
    gerar_fabrica_embalagens, gerar_farmacia_manipulacao, gerar_feira_livre, gerar_ferrovia_carga,
    gerar_floricultura, gerar_food_truck, gerar_igreja, gerar_industria_moveleira,
    gerar_industria_naval, gerar_lavanderia, gerar_manutencao_industrial, gerar_motoboy,
    gerar_multipropriedade, gerar_plano_saude, gerar_padaria, gerar_parque_diversoes,
    gerar_porto, gerar_posto_combustivel, gerar_radio_podcast, gerar_relacoes_publicas,
    gerar_serralheria, gerar_limpeza, gerar_sindicato, gerar_taxi_aereo,
    gerar_telemedicina, gerar_transporte_escolar, gerar_usina_acucar_etanol, gerar_vending_machine,
    gerar_viveiro_paisagismo, gerar_zoologico,
    # ═══════ +50 NOVOS SETORES (LOTE 7) ═══════
    gerar_aeroporto, gerar_agencia_noticias, gerar_asilo, gerar_atacado,
    gerar_autoescola, gerar_avicultura, gerar_banco_sangue, gerar_boliche,
    gerar_cafeicultura, gerar_calcados, gerar_casa_noturna, gerar_cemiterio,
    gerar_ceramica, gerar_cerealista, gerar_circo, gerar_clube_social,
    gerar_cobranca, gerar_cosmeticos, gerar_creche, gerar_curtume,
    gerar_despachante_aduaneiro, gerar_distribuidora_bebidas, gerar_engenharia, gerar_escola_tecnica,
    gerar_estadio, gerar_fabrica_brinquedos, gerar_fabrica_pneus, gerar_financeira,
    gerar_fisioterapia, gerar_gas_natural, gerar_gestora_fundos, gerar_impressao_3d,
    gerar_incorporadora, gerar_inspecao_certificacao, gerar_livraria, gerar_marina,
    gerar_onibus_intermunicipal, gerar_pedagio, gerar_controle_pragas, gerar_plasticos,
    gerar_resseguradora, gerar_robotica, gerar_seguranca_eletronica, gerar_shopping_center,
    gerar_sorveteria, gerar_vidracaria, gerar_agua_mineral, gerar_bike_sharing,
    gerar_manutencao_elevadores, gerar_seguranca_trabalho,
)

# Configuração da página Streamlit
PAGE_CONFIG = {
    "page_title": "BI Data Generator PRO",
    "page_icon": "📊",
    "layout": "wide",
    "initial_sidebar_state": "expanded"
}

# Configurações do slider de linhas
SLIDER_MIN = 100
SLIDER_MAX = 100000
SLIDER_DEFAULT = 5000
SLIDER_STEP = 100

# ═══════════════════════════════════════════════════════════════
# Dicionário de setores disponíveis (200 setores) — ordem alfabética
# ═══════════════════════════════════════════════════════════════
SETORES = {
    "🏋️ Academia & Fitness": gerar_academia,
    "🛫 Aeroporto & Operações Aeroportuárias": gerar_aeroporto,
    "💱 Agência de Câmbio": gerar_agencia_cambio,
    "📰 Agência de Notícias": gerar_agencia_noticias,
    "📢 Agência de Publicidade": gerar_agencia_publicidade,
    "🌾 Agronegócio": gerar_agronegocio,
    "🌱 AgTech": gerar_agtech,
    "🚰 Água Mineral & Envasamento": gerar_agua_mineral,
    "🍔 Alimentos & Bebidas": gerar_alimenticio,
    "🚲 Aluguel de Bicicletas & Bike Sharing": gerar_bike_sharing,
    "🚑 Ambulância & Remoção": gerar_ambulancia,
    "🐝 Apicultura": gerar_apicultura,
    "🎰 Apostas Esportivas & iGaming": gerar_apostas_esportivas,
    "🏬 Armazenagem & Self Storage": gerar_armazenagem,
    "🏛️ Arquitetura & Design": gerar_arquitetura,
    "🧶 Artesanato": gerar_artesanato,
    "👵 Asilo & Casa de Repouso": gerar_asilo,
    "🔩 Assistência Técnica de Eletrônicos": gerar_assistencia_tecnica,
    "🛍️ Atacado & Atacarejo": gerar_atacado,
    "🎬 Audiovisual & Produtora": gerar_audiovisual,
    "🕵️ Auditoria & Compliance": gerar_auditoria,
    "🚦 Autoescola": gerar_autoescola,
    "🔧 Autopeças & Oficina Mecânica": gerar_autopecas,
    "✈️ Aviação Civil": gerar_aviacao,
    "🐔 Avicultura": gerar_avicultura,
    "🩸 Banco de Sangue & Hemocentro": gerar_banco_sangue,
    "💈 Barbearia": gerar_barbearia,
    "💄 Beleza & Estética": gerar_beleza,
    "🌽 Biocombustíveis": gerar_biocombustiveis,
    "🧬 Biotecnologia": gerar_biotecnologia,
    "🪙 Blockchain & Criptomoedas": gerar_blockchain,
    "🎳 Boliche & Diversão Familiar": gerar_boliche,
    "🍱 Buffet & Cerimonial": gerar_buffet,
    "☕ Cafeicultura & Torrefação": gerar_cafeicultura,
    "👟 Calçados": gerar_calcados,
    "📞 Call Center & BPO": gerar_call_center,
    "📜 Cartório & Serviços Notariais": gerar_cartorio,
    "🎫 Casa Lotérica & Correspondente Bancário": gerar_casa_loterica,
    "🪩 Casa Noturna & Casa de Shows": gerar_casa_noturna,
    "🪦 Cemitério & Serviços Perpétuos": gerar_cemiterio,
    "🧱 Cerâmica & Revestimentos": gerar_ceramica,
    "🌾 Cerealista & Armazém de Grãos": gerar_cerealista,
    "🍺 Cervejaria Artesanal": gerar_cervejaria,
    "🔐 Cibersegurança": gerar_ciberseguranca,
    "🎥 Cinema & Exibição": gerar_cinema,
    "🎪 Circo & Espetáculos Itinerantes": gerar_circo,
    "🎁 Clube de Assinaturas": gerar_clube_assinatura,
    "🎾 Clube Social & Recreativo": gerar_clube_social,
    "📇 Cobrança & Recuperação de Crédito": gerar_cobranca,
    "🌐 Comércio Exterior": gerar_comercio_exterior,
    "🚙 Concessionária de Veículos": gerar_concessionaria,
    "🏢 Condomínio & Facilities": gerar_condominio,
    "🧾 Consórcios": gerar_consorcio,
    "🏗️ Construção Civil": gerar_construcao,
    "📊 Consultoria Empresarial": gerar_consultoria,
    "🧮 Contabilidade": gerar_contabilidade,
    "🐜 Controle de Pragas & Dedetização": gerar_controle_pragas,
    "💳 Cooperativa de Crédito": gerar_cooperativa_credito,
    "📦 Correios & Encomendas": gerar_correios,
    "📈 Corretora de Investimentos": gerar_corretora_investimentos,
    "🧴 Cosméticos & Fábrica de Cosméticos": gerar_cosmeticos,
    "🪑 Coworking & Espaços Compartilhados": gerar_coworking,
    "👶 Creche & Educação Infantil": gerar_creche,
    "🤝 CRM": gerar_crm,
    "📝 Cursinho Preparatório": gerar_cursinho,
    "🟫 Curtume & Couro": gerar_curtume,
    "🖥️ Data Center & Cloud Hosting": gerar_datacenter,
    "🛵 Delivery de Comida": gerar_delivery,
    "🛃 Despachante Aduaneiro": gerar_despachante_aduaneiro,
    "🍹 Distribuidora de Bebidas": gerar_distribuidora_bebidas,
    "🚁 Drones & Serviços Aéreos": gerar_drones,
    "🏪 E-commerce": gerar_ecommerce,
    "♻️ Economia Circular": gerar_economia_circular,
    "📖 Editora & Publicação": gerar_editora,
    "📚 Educação": gerar_educacao,
    "⚡ Energia": gerar_energia,
    "☀️ Energia Solar": gerar_energia_solar,
    "📐 Engenharia & Projetos": gerar_engenharia,
    "🎓 Ensino Superior": gerar_ensino_superior,
    "🗣️ Escola de Idiomas": gerar_escola_idiomas,
    "🎼 Escola de Música": gerar_escola_musica,
    "🧰 Escola Técnica & Profissionalizante": gerar_escola_tecnica,
    "🚀 Espacial & Aeroespacial": gerar_espacial,
    "🏟️ Esportes": gerar_esportes,
    "🅿️ Estacionamento & Zona Azul": gerar_estacionamento,
    "🏟️ Estádio & Arena": gerar_estadio,
    "🖋️ Estúdio de Tatuagem": gerar_estudio_tatuagem,
    "🎉 Eventos & Entretenimento": gerar_eventos,
    "🪀 Fábrica de Brinquedos": gerar_fabrica_brinquedos,
    "📦 Fábrica de Embalagens": gerar_fabrica_embalagens,
    "🛞 Fábrica de Pneus & Borracha": gerar_fabrica_pneus,
    "💊 Farmacêutico": gerar_farmaceutico,
    "⚗️ Farmácia de Manipulação": gerar_farmacia_manipulacao,
    "🥬 Feira Livre & Mercado Municipal": gerar_feira_livre,
    "🚂 Ferrovia de Carga": gerar_ferrovia_carga,
    "💵 Financeira & Crédito Pessoal": gerar_financeira,
    "💰 Financeiro": gerar_financeiro,
    "🏦 Fintech": gerar_fintech,
    "🦵 Fisioterapia & Reabilitação": gerar_fisioterapia,
    "🌲 Florestal & Papel": gerar_florestal,
    "💐 Floricultura": gerar_floricultura,
    "🌮 Food Truck": gerar_food_truck,
    "🏷️ Franquias": gerar_franquias,
    "🥩 Frigorífico & Processamento de Carnes": gerar_frigorifico,
    "⚰️ Funerária & Serviços Funerários": gerar_funeraria,
    "🎮 Games & eSports": gerar_games,
    "🔥 Gás Natural & Distribuição": gerar_gas_natural,
    "💹 Gestora de Fundos & Asset Management": gerar_gestora_fundos,
    "🏛️ Governo & Setor Público": gerar_governo,
    "🖨️ Gráfica & Comunicação Visual": gerar_grafica,
    "🩺 Home Care": gerar_homecare,
    "🏨 Hotelaria": gerar_hotelaria,
    "⛪ Igreja & Templos Religiosos": gerar_igreja,
    "🏠 Imobiliário": gerar_imobiliario,
    "🧊 Impressão 3D & Prototipagem": gerar_impressao_3d,
    "🏙️ Incorporadora Imobiliária": gerar_incorporadora,
    "🏭 Indústria": gerar_industria,
    "🛋️ Indústria Moveleira": gerar_industria_moveleira,
    "🚢 Indústria Naval": gerar_industria_naval,
    "✅ Inspeção & Certificação": gerar_inspecao_certificacao,
    "💍 Joalheria & Relojoaria": gerar_joalheria,
    "⚖️ Jurídico": gerar_juridico,
    "🔬 Laboratório & Diagnóstico": gerar_laboratorio,
    "🧺 Lavanderia": gerar_lavanderia,
    "🔨 Leilão": gerar_leilao,
    "📕 Livraria": gerar_livraria,
    "🛠️ Locação de Equipamentos": gerar_locacao_equipamentos,
    "🏖️ Locação por Temporada": gerar_locacao_temporada,
    "🚗 Locadora de Veículos": gerar_locadora,
    "🚚 Logística": gerar_logistica,
    "🚴 Logística Urbana": gerar_logistica_urbana,
    "🛗 Manutenção de Elevadores": gerar_manutencao_elevadores,
    "🛠️ Manutenção Industrial": gerar_manutencao_industrial,
    "🪵 Marcenaria & Móveis Planejados": gerar_marcenaria,
    "⛵ Marina & Náutica": gerar_marina,
    "📣 Marketing Digital": gerar_marketing,
    "⚙️ Metalurgia & Siderurgia": gerar_metalurgia,
    "🚇 Metrô & Trem Urbano": gerar_metro,
    "📲 Migração Claro Brasil (Portabilidade)": gerar_portabilidade_claro,
    "⛏️ Mineração": gerar_mineracao,
    "🚗 Mobilidade": gerar_mobilidade,
    "👗 Moda & Vestuário": gerar_moda,
    "🏍️ Motoboy & App de Transporte": gerar_motoboy,
    "🏝️ Multipropriedade": gerar_multipropriedade,
    "🖼️ Museus & Cultura": gerar_museus,
    "🦷 Odontologia": gerar_odontologia,
    "🚍 Ônibus Intermunicipal & Rodoviária": gerar_onibus_intermunicipal,
    "🗂️ Operadora de Plano de Saúde": gerar_plano_saude,
    "👓 Óptica": gerar_optica,
    "🥐 Padaria & Confeitaria": gerar_padaria,
    "📎 Papelaria & Material Escolar": gerar_papelaria,
    "🎡 Parque de Diversões": gerar_parque_diversoes,
    "🐄 Pecuária": gerar_pecuaria,
    "🛣️ Pedágio & Concessão Rodoviária": gerar_pedagio,
    "🐟 Pesca & Aquicultura": gerar_pesca,
    "🐾 Pet & Veterinária": gerar_pet,
    "🛢️ Petróleo & Gás": gerar_petroleo,
    "🏊 Piscina & Spa": gerar_piscina_spa,
    "🧪 Plásticos & Fábrica de Plásticos": gerar_plasticos,
    "⚓ Porto & Terminal Portuário": gerar_porto,
    "⛽ Posto de Combustível & Conveniência": gerar_posto_combustivel,
    "🎙️ Rádio & Podcast": gerar_radio_podcast,
    "🗑️ Reciclagem & Gestão de Resíduos": gerar_reciclagem,
    "🏢 Recursos Humanos": gerar_rh,
    "📰 Relações Públicas": gerar_relacoes_publicas,
    "🔁 Resseguradora": gerar_resseguradora,
    "🍽️ Restaurantes & Food Service": gerar_restaurante,
    "🤖 Robótica & Automação Industrial": gerar_robotica,
    "☁️ SaaS B2B": gerar_saas_b2b,
    "💧 Saneamento & Água": gerar_saneamento,
    "🏥 Saúde": gerar_saude,
    "🧠 Saúde Mental": gerar_saude_mental,
    "🦺 Segurança do Trabalho & SESMT": gerar_seguranca_trabalho,
    "📹 Segurança Eletrônica & Monitoramento": gerar_seguranca_eletronica,
    "🔒 Segurança Privada": gerar_seguranca_privada,
    "🛡️ Seguros": gerar_seguros,
    "⚒️ Serralheria": gerar_serralheria,
    "🧹 Serviços de Limpeza": gerar_limpeza,
    "🏬 Shopping Center & Administração de Malls": gerar_shopping_center,
    "🪧 Sindicato & Associação de Classe": gerar_sindicato,
    "🍦 Sorveteria & Fábrica de Sorvetes": gerar_sorveteria,
    "🦄 Startups & Venture Capital": gerar_startup,
    "🎬 Streaming": gerar_streaming,
    "🛩️ Táxi Aéreo & Aviação Executiva": gerar_taxi_aereo,
    "💻 Tecnologia": gerar_tecnologia,
    "📡 Telecom": gerar_telecom,
    "🖥️ Telemedicina": gerar_telemedicina,
    "🤲 Terceiro Setor & ONGs": gerar_terceiro_setor,
    "🧵 Têxtil & Confecção": gerar_textil,
    "🚛 Transporte": gerar_transporte,
    "🚌 Transporte Escolar": gerar_transporte_escolar,
    "✈️ Turismo": gerar_turismo,
    "🍬 Usina de Açúcar & Etanol": gerar_usina_acucar_etanol,
    "🛒 Varejo": gerar_varejo,
    "🥤 Vending Machine & Autoatendimento": gerar_vending_machine,
    "✈️ Viagens Corporativas": gerar_viagem_corp,
    "🪟 Vidraçaria & Fábrica de Vidros": gerar_vidracaria,
    "🍷 Vinícola & Vitivinicultura": gerar_vinicola,
    "🌳 Viveiro & Paisagismo": gerar_viveiro_paisagismo,
    "🦁 Zoológico & Aquário": gerar_zoologico,
}

# ═══════════════════════════════════════════════════════════════
# Informações para os flip-cards da tela inicial (200 setores) — ordem alfabética
# ═══════════════════════════════════════════════════════════════
SETORES_INFO = [
    ("🏋️", "Academia & Fitness", "Check-ins, alunos, instrutores, pagamentos e avaliações físicas"),
    ("🛫", "Aeroporto & Operações Aeroportuárias", "Aeroportos, terminais, pousos e decolagens, companhias aéreas"),
    ("💱", "Agência de Câmbio", "Operações de câmbio, moedas, cotações e taxas de serviço"),
    ("📰", "Agência de Notícias", "Jornalistas, matérias, veículos assinantes e distribuição"),
    ("📢", "Agência de Publicidade", "Projetos, campanhas de mídia, equipe e clientes"),
    ("🌾", "Agronegócio", "Safras, culturas, propriedades e insumos"),
    ("🌱", "AgTech", "Sensores IoT, drones, monitoramento e agricultura de precisão"),
    ("🚰", "Água Mineral & Envasamento", "Fontes, linhas envasadas, produção e distribuição"),
    ("🍔", "Alimentos & Bebidas", "Produção, plantas, produtos e fornecedores"),
    ("🚲", "Aluguel de Bicicletas & Bike Sharing", "Estações, bicicletas, corridas e planos"),
    ("🚑", "Ambulância & Remoção", "Chamados de emergência, ambulâncias, equipes e tempo de resposta"),
    ("🐝", "Apicultura", "Apiários, colmeias, colheita de mel e sanidade"),
    ("🎰", "Apostas Esportivas & iGaming", "Apostas, jogadores, eventos esportivos e transações"),
    ("🏬", "Armazenagem & Self Storage", "Unidades, boxes, contratos e ocorrências de armazenagem"),
    ("🏛️", "Arquitetura & Design", "Projetos, serviços, honorários e gestão de obras"),
    ("🧶", "Artesanato", "Artesãos, produtos, vendas por canal e produção"),
    ("👵", "Asilo & Casa de Repouso", "Instituições, residentes, cuidadores e ocorrências de saúde"),
    ("🔩", "Assistência Técnica de Eletrônicos", "Ordens de serviço, técnicos, peças e reparos"),
    ("🛍️", "Atacado & Atacarejo", "Lojas, produtos a granel, vendas B2B e clientes"),
    ("🎬", "Audiovisual & Produtora", "Produções, orçamentos, recursos e bilheteria"),
    ("🕵️", "Auditoria & Compliance", "Auditores, clientes, achados e não conformidades"),
    ("🚦", "Autoescola", "Unidades, instrutores, aulas e exames de habilitação"),
    ("🔧", "Autopeças & Oficina Mecânica", "Peças, serviços, clientes e canais de venda"),
    ("✈️", "Aviação Civil", "Voos, passageiros, aeronaves e aeroportos"),
    ("🐔", "Avicultura", "Granjas, lotes de aves, produção e mortalidade"),
    ("🩸", "Banco de Sangue & Hemocentro", "Unidades, doadores, doações e tipos sanguíneos"),
    ("💈", "Barbearia", "Barbeiros, unidades, atendimentos e assinaturas"),
    ("💄", "Beleza & Estética", "Vendas, serviços, agenda e salões parceiros"),
    ("🌽", "Biocombustíveis", "Usinas, matérias-primas, produção e vendas de combustível"),
    ("🧬", "Biotecnologia", "Genômica, CRISPR, pesquisa e experimentos laboratoriais"),
    ("🪙", "Blockchain & Criptomoedas", "Transações, moedas, usuários e carteiras digitais"),
    ("🎳", "Boliche & Diversão Familiar", "Unidades, pistas, partidas e clientes"),
    ("🍱", "Buffet & Cerimonial", "Eventos, cardápios, fornecedores e cerimonial"),
    ("☕", "Cafeicultura & Torrefação", "Fazendas, lotes de café, colheita e torrefação"),
    ("👟", "Calçados", "Fábricas, modelos, produção e vendas por canal"),
    ("📞", "Call Center & BPO", "Atendimentos, atendentes, clientes e avaliação de qualidade"),
    ("📜", "Cartório & Serviços Notariais", "Atos notariais, tabeliães, clientes e protestos"),
    ("🎫", "Casa Lotérica & Correspondente Bancário", "Transações, apostas de loteria, unidades e serviços"),
    ("🪩", "Casa Noturna & Casa de Shows", "Casas, eventos, ingressos e consumo no bar"),
    ("🪦", "Cemitério & Serviços Perpétuos", "Cemitérios, jazigos, sepultamentos e manutenção"),
    ("🧱", "Cerâmica & Revestimentos", "Fábricas, linhas de produto, produção e vendas"),
    ("🌾", "Cerealista & Armazém de Grãos", "Armazéns, produtores, recebimento e classificação de grãos"),
    ("🍺", "Cervejaria Artesanal", "Rótulos, pontos de venda, produção e vendas"),
    ("🔐", "Cibersegurança", "Incidentes, vulnerabilidades, ativos e SLA de resposta (SOC)"),
    ("🎥", "Cinema & Exibição", "Sessões, filmes, salas e bomboniere"),
    ("🎪", "Circo & Espetáculos Itinerantes", "Trupes, turnês, sessões e público"),
    ("🎁", "Clube de Assinaturas", "Assinantes, caixas temáticas, planos e envios"),
    ("🎾", "Clube Social & Recreativo", "Clubes, sócios, instalações e mensalidades"),
    ("📇", "Cobrança & Recuperação de Crédito", "Carteiras de dívida, devedores e negociações"),
    ("🌐", "Comércio Exterior", "Produtos, países, importações e exportações"),
    ("🚙", "Concessionária de Veículos", "Vendas, veículos, vendedores e test-drives"),
    ("🏢", "Condomínio & Facilities", "Cotas, despesas, ocorrências e manutenção"),
    ("🧾", "Consórcios", "Parcelas, contemplações, grupos e cotistas"),
    ("🏗️", "Construção Civil", "Obras, custos, materiais e fornecedores"),
    ("📊", "Consultoria Empresarial", "Projetos, consultores, faturas e clientes"),
    ("🧮", "Contabilidade", "Contadores, clientes PJ, serviços e honorários"),
    ("🐜", "Controle de Pragas & Dedetização", "Técnicos, clientes, ordens de serviço e tipo de praga"),
    ("💳", "Cooperativa de Crédito", "Operações, cooperados, produtos e sobras distribuídas"),
    ("📦", "Correios & Encomendas", "Envios, agências, serviços e ocorrências"),
    ("📈", "Corretora de Investimentos", "Assessores, clientes, ativos, ordens e carteiras"),
    ("🧴", "Cosméticos & Fábrica de Cosméticos", "Linhas de produto, produção, canais e vendas"),
    ("🪑", "Coworking & Espaços Compartilhados", "Reservas, assinaturas, espaços e clientes"),
    ("👶", "Creche & Educação Infantil", "Unidades, turmas, matrículas e mensalidades"),
    ("🤝", "CRM", "Oportunidades, contas, contatos e atividades comerciais"),
    ("📝", "Cursinho Preparatório", "Professores, alunos, matrículas e simulados"),
    ("🟫", "Curtume & Couro", "Curtumes, lotes de couro, processamento e vendas"),
    ("🖥️", "Data Center & Cloud Hosting", "Consumo, instâncias, clientes e incidentes"),
    ("🛵", "Delivery de Comida", "Restaurantes parceiros, entregadores, pedidos e avaliações"),
    ("🛃", "Despachante Aduaneiro", "Despachantes, clientes, processos de importação e exportação"),
    ("🍹", "Distribuidora de Bebidas", "Centros de distribuição, marcas, pedidos de bares e mercados"),
    ("🚁", "Drones & Serviços Aéreos", "Missões, drones, manutenção e clientes"),
    ("🏪", "E-commerce", "Pedidos, clientes, produtos, fretes e pagamentos"),
    ("♻️", "Economia Circular", "Reciclagem, logística reversa, créditos de carbono e ESG"),
    ("📖", "Editora & Publicação", "Livros, vendas, canais e estoque"),
    ("📚", "Educação", "Matrículas, alunos, cursos e instrutores"),
    ("⚡", "Energia", "Consumo, medidores, subestações e tarifas"),
    ("☀️", "Energia Solar", "Instalações, clientes, geração e projetos fotovoltaicos"),
    ("📐", "Engenharia & Projetos", "Escritórios, engenheiros, projetos e contratos"),
    ("🎓", "Ensino Superior", "Matrículas, disciplinas, cursos e desempenho acadêmico"),
    ("🗣️", "Escola de Idiomas", "Professores, alunos, cursos, matrículas e avaliações"),
    ("🎼", "Escola de Música", "Professores, alunos, instrumentos, aulas e matrículas"),
    ("🧰", "Escola Técnica & Profissionalizante", "Unidades, cursos técnicos, alunos e estágios"),
    ("🚀", "Espacial & Aeroespacial", "Missões, satélites, lançamentos e operações"),
    ("🏟️", "Esportes", "Partidas, atletas, clubes e competições"),
    ("🅿️", "Estacionamento & Zona Azul", "Entradas, estacionamentos, clientes e multas"),
    ("🏟️", "Estádio & Arena", "Arenas, eventos, ingressos e bilheteria"),
    ("🖋️", "Estúdio de Tatuagem", "Tatuadores, clientes, sessões e retornos"),
    ("🎉", "Eventos & Entretenimento", "Ingressos, fornecedores, receitas e NPS"),
    ("🪀", "Fábrica de Brinquedos", "Linhas de brinquedos, produção e pedidos de lojas"),
    ("📦", "Fábrica de Embalagens", "Produtos, clientes PJ, produção e pedidos"),
    ("🛞", "Fábrica de Pneus & Borracha", "Fábricas, modelos de pneu, produção e vendas"),
    ("💊", "Farmacêutico", "Produtos, representantes, vendas e estoque"),
    ("⚗️", "Farmácia de Manipulação", "Farmacêuticos, clientes, fórmulas e insumos"),
    ("🥬", "Feira Livre & Mercado Municipal", "Feirantes, bancas, vendas e ocupação"),
    ("🚂", "Ferrovia de Carga", "Locomotivas, terminais, viagens de carga e manutenção"),
    ("💵", "Financeira & Crédito Pessoal", "Agências, clientes, contratos de empréstimo e parcelas"),
    ("💰", "Financeiro", "Transações bancárias, contas e agências"),
    ("🏦", "Fintech", "Transações, cartões, usuários, comerciantes e antifraude"),
    ("🦵", "Fisioterapia & Reabilitação", "Clínicas, fisioterapeutas, pacientes e sessões"),
    ("🌲", "Florestal & Papel", "Talhões, espécies, colheita e carbono"),
    ("💐", "Floricultura", "Lojas, produtos, vendas e encomendas especiais"),
    ("🌮", "Food Truck", "Trucks, cardápio, vendas e eventos"),
    ("🏷️", "Franquias", "Unidades, royalties, taxas e faturamento"),
    ("🥩", "Frigorífico & Processamento de Carnes", "Abate, produtos, unidades e canais de venda"),
    ("⚰️", "Funerária & Serviços Funerários", "Atendimentos, serviços, planos preventivos e clientes"),
    ("🎮", "Games & eSports", "Partidas, jogadores, jogos e monetização in-game"),
    ("🔥", "Gás Natural & Distribuição", "Distribuidoras, ligações, consumo e faturas"),
    ("💹", "Gestora de Fundos & Asset Management", "Fundos, cotistas, aportes e resgates"),
    ("🏛️", "Governo & Setor Público", "Despesas, receitas, licitações e contratos"),
    ("🖨️", "Gráfica & Comunicação Visual", "Pedidos, produção, produtos e clientes"),
    ("🩺", "Home Care", "Visitas, pacientes, profissionais e ocorrências"),
    ("🏨", "Hotelaria", "Reservas, hóspedes, hotéis, quartos e canais"),
    ("⛪", "Igreja & Templos Religiosos", "Membros, ministérios, dízimos e eventos"),
    ("🏠", "Imobiliário", "Vendas, aluguéis, imóveis e corretores"),
    ("🧊", "Impressão 3D & Prototipagem", "Empresas, impressoras, materiais e pedidos"),
    ("🏙️", "Incorporadora Imobiliária", "Empreendimentos, unidades, vendas na planta e forma de pagamento"),
    ("🏭", "Indústria", "Produção, máquinas, insumos e operadores"),
    ("🛋️", "Indústria Moveleira", "Produtos, máquinas, produção e vendas"),
    ("🚢", "Indústria Naval", "Estaleiros, embarcações, etapas de construção e manutenção"),
    ("✅", "Inspeção & Certificação", "Inspetores, empresas clientes, auditorias e certificações"),
    ("💍", "Joalheria & Relojoaria", "Vendas, produtos, clientes e assistência técnica"),
    ("⚖️", "Jurídico", "Processos, advogados, clientes e tribunais"),
    ("🔬", "Laboratório & Diagnóstico", "Exames, pacientes, laudos e convênios"),
    ("🧺", "Lavanderia", "Unidades, clientes B2B, pedidos e ocorrências"),
    ("🔨", "Leilão", "Lances, lotes, arrematantes e arrematações"),
    ("📕", "Livraria", "Lojas, livros, gêneros e vendas"),
    ("🛠️", "Locação de Equipamentos", "Locações, equipamentos, manutenção e clientes"),
    ("🏖️", "Locação por Temporada", "Reservas, imóveis, hóspedes e avaliações"),
    ("🚗", "Locadora de Veículos", "Reservas, frota, clientes, multas e diárias"),
    ("🚚", "Logística", "Entregas, transportadoras, rotas e clientes"),
    ("🚴", "Logística Urbana", "Entregas last mile, entregadores e SLA"),
    ("🛗", "Manutenção de Elevadores", "Técnicos, elevadores, chamados e tempo de atendimento"),
    ("🛠️", "Manutenção Industrial", "Técnicos, clientes, ordens de serviço e peças"),
    ("🪵", "Marcenaria & Móveis Planejados", "Contratos, projetos, produção e clientes"),
    ("⛵", "Marina & Náutica", "Marinas, embarcações, vagas e atracações"),
    ("📣", "Marketing Digital", "Campanhas, canais, performance e conversões"),
    ("⚙️", "Metalurgia & Siderurgia", "Produção, fornos, produtos e vendas"),
    ("🚇", "Metrô & Trem Urbano", "Validações, estações, linhas e ocorrências"),
    ("📲", "Migração Claro Brasil (Portabilidade)", "Migrações IN/OUT, serviços, operadoras e motivos de portabilidade"),
    ("⛏️", "Mineração", "Extrações, minas, minerais e equipamentos"),
    ("🚗", "Mobilidade", "Viagens, motoristas, passageiros, rotas e veículos"),
    ("👗", "Moda & Vestuário", "Coleções, vendas, estoque e devoluções"),
    ("🏍️", "Motoboy & App de Transporte", "Motociclistas, clientes e corridas de entrega/passageiro"),
    ("🏝️", "Multipropriedade", "Resorts, unidades, proprietários, reservas e taxas"),
    ("🖼️", "Museus & Cultura", "Visitas, exposições, eventos culturais e ingressos"),
    ("🦷", "Odontologia", "Consultas, dentistas, pacientes, procedimentos e convênios"),
    ("🚍", "Ônibus Intermunicipal & Rodoviária", "Empresas, linhas, viagens e passageiros"),
    ("🗂️", "Operadora de Plano de Saúde", "Beneficiários, planos, prestadores, autorizações e mensalidades"),
    ("👓", "Óptica", "Vendas, produtos, clientes e exames de vista"),
    ("🥐", "Padaria & Confeitaria", "Lojas, produtos, vendas e produção"),
    ("📎", "Papelaria & Material Escolar", "Vendas, produtos, lojas e estoque"),
    ("🎡", "Parque de Diversões", "Brinquedos, ingressos e uso dos brinquedos"),
    ("🐄", "Pecuária", "Fazendas, rebanho, manejo e produção"),
    ("🛣️", "Pedágio & Concessão Rodoviária", "Concessionárias, praças, passagens e arrecadação"),
    ("🐟", "Pesca & Aquicultura", "Espécies, produção, qualidade e biomassa"),
    ("🐾", "Pet & Veterinária", "Atendimentos, pets, tutores e serviços veterinários"),
    ("🛢️", "Petróleo & Gás", "Produção, poços, plataformas e custos operacionais"),
    ("🏊", "Piscina & Spa", "Serviços, clientes, técnicos e consumo de produtos químicos"),
    ("🧪", "Plásticos & Fábrica de Plásticos", "Fábricas, produtos plásticos, produção e vendas"),
    ("⚓", "Porto & Terminal Portuário", "Terminais, navios, atracações e movimentação de carga"),
    ("⛽", "Posto de Combustível & Conveniência", "Postos, combustíveis, abastecimentos e loja de conveniência"),
    ("🎙️", "Rádio & Podcast", "Programas, apresentadores, audiência e anúncios"),
    ("🗑️", "Reciclagem & Gestão de Resíduos", "Coletas, materiais, cooperativas e vendas de material"),
    ("🏢", "Recursos Humanos", "Horas trabalhadas, funcionários, projetos e cargos"),
    ("📰", "Relações Públicas", "Clientes, veículos de mídia, assessoria e clipping"),
    ("🔁", "Resseguradora", "Seguradoras cedentes, tratados e sinistros ressegurados"),
    ("🍽️", "Restaurantes & Food Service", "Pedidos, cardápio, unidades, reservas e delivery"),
    ("🤖", "Robótica & Automação Industrial", "Fábricas clientes, robôs e projetos de automação"),
    ("☁️", "SaaS B2B", "Assinaturas, MRR, churn, NPS e planos"),
    ("💧", "Saneamento & Água", "Consumo, faturas, estações de tratamento e ligações"),
    ("🏥", "Saúde", "Atendimentos, pacientes, médicos e procedimentos"),
    ("🧠", "Saúde Mental", "Sessões, profissionais, pacientes e diagnósticos"),
    ("🦺", "Segurança do Trabalho & SESMT", "Empresas clientes, exames ocupacionais e treinamentos NR"),
    ("📹", "Segurança Eletrônica & Monitoramento", "Centrais, clientes, alarmes e tempo de resposta"),
    ("🔒", "Segurança Privada", "Escalações, vigilantes, clientes e ocorrências"),
    ("🛡️", "Seguros", "Apólices, segurados, corretores e sinistros"),
    ("⚒️", "Serralheria", "Clientes, produtos, pedidos e produção"),
    ("🧹", "Serviços de Limpeza", "Funcionários, contratos, atendimentos e insumos"),
    ("🏬", "Shopping Center & Administração de Malls", "Shoppings, lojistas, aluguel e fluxo de visitantes"),
    ("🪧", "Sindicato & Associação de Classe", "Associados, categorias, contribuições e benefícios"),
    ("🍦", "Sorveteria & Fábrica de Sorvetes", "Fábricas, sabores, produção e vendas"),
    ("🦄", "Startups & Venture Capital", "Rodadas, valuations, MRR e métricas de crescimento"),
    ("🎬", "Streaming", "Plays, assinantes, conteúdos, artistas"),
    ("🛩️", "Táxi Aéreo & Aviação Executiva", "Aeronaves, pilotos, voos fretados e manutenção"),
    ("💻", "Tecnologia", "Contratos SaaS, clientes e planos"),
    ("📡", "Telecom", "Chamadas, assinantes, planos e torres"),
    ("🖥️", "Telemedicina", "Médicos, pacientes, teleconsultas e prescrições"),
    ("🤲", "Terceiro Setor & ONGs", "Doações, projetos sociais, doadores e execução"),
    ("🧵", "Têxtil & Confecção", "Fibras, produção, eficiência e clientes"),
    ("🚛", "Transporte", "Viagens, frota, combustível, manutenção e rentabilidade"),
    ("🚌", "Transporte Escolar", "Veículos, motoristas, alunos, rotas e mensalidades"),
    ("✈️", "Turismo", "Viagens, pacotes, agências e destinos"),
    ("🍬", "Usina de Açúcar & Etanol", "Usinas, talhões, moagem e produção"),
    ("🛒", "Varejo", "Vendas, clientes, produtos e filiais"),
    ("🥤", "Vending Machine & Autoatendimento", "Máquinas, produtos, vendas e reposição"),
    ("✈️", "Viagens Corporativas", "Viajantes, custos, política de viagem e SLA"),
    ("🪟", "Vidraçaria & Fábrica de Vidros", "Fábricas, produtos de vidro, pedidos e instalação"),
    ("🍷", "Vinícola & Vitivinicultura", "Produção, vinhedos, vinhos e canais de venda"),
    ("🌳", "Viveiro & Paisagismo", "Plantas, clientes, vendas e projetos de paisagismo"),
    ("🦁", "Zoológico & Aquário", "Recintos, animais, ingressos e manejo"),
]

# Configurações de datas (opcional)
DATE_DEFAULT_START = "2023-01-01"
DATE_DEFAULT_END   = "2023-12-31"
